name: Continous Integration

on: pull_request

jobs:
  continius_integrations:
    runs-on: ubunto-latest

    steps:
      - uses: actions/checkout@v3
      - name: use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.
      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test 